### PR TITLE
Update logo & colors

### PR DESCRIPTION
**Pull request by filiph**

### CODE REVIEW

**Comment by sethladd** [comment]
Thanks! Please run the PNGs through optipng (or similar)

**Comment by filiph** [comment]
PNGs are now compressed with zopfli.

**Comment by Hixie** [comment]
RSLGTM

**Comment by maguinis** [comment]
LGTM

**Comment by filiph** [comment]
cc @sethladd I can't merge this, I don't have the rights. Could you?

**Comment by sethladd** [comment]
maybe @Hixie can help setup the permissions for you?

**Comment by Hixie** [comment]
Try now.

**Pull request merged**
